resources:
  - mysql.yaml
  - firefly-iii.yaml
  - ingress-firefly-iii-cron.yaml
  - firefly-iii-importer.yaml
secretGenerator:
- name: firefly-iii-secrets
  literals:
  - db_password=CHANGEMECHANGEME
  - app_key=CHANGEMECHANGEMECHANGEMECHANGEME
  - access_token=CHANGEMECHANGEMECHANGEME...
  - static_cron_token=CHANGE12CHAR
