firefly-db:
  # if you set this to false it will not be installed
  enabled: true
  image:
    repository: postgres
    tag: 10-alpine
    pullPolicy: IfNotPresent

  # environment variables
  configs:
    RESTORE_URL: ""
    BACKUP_URL: ""
    PGPASSWORD: "YOURDBPASSWORD"
    DBHOST: firefly-firefly-db
    DBPORT: "5432"
    DBNAME: firefly
    DBUSER: firefly
    TZ: Europe/Berlin

  backupSchedule: "0 3 * * *"
  fullnameOverride: firefly-db

firefly-iii:
  # -- Set to false to not deploy Firefly III
  enabled: true
  dbNameOverride: firefly-db
  config:
    # -- Directly defined environment variables. Use this for non-secret configuration values.
    env:
      APP_KEY: "SomeRandomStringOf32CharsExactly"

importer:
  # -- Set to false to not deploy the importer
  enabled: true
